export const ROUTES = {
  home: "/",
  about: "/about",
  contact: "/contact",
  pricing: "/pricing",
  blog: "/blog",
  blogGrid: "/blog/grid",
  blogPost: (slug: string) => `/blog/${slug}`,
  howItWorks: "/#how-it-works",
  features: "/#features",
  safety: "/#safety",
  download: "/#download",
  careers: "/careers",
  partners: "/partners",
  press: "/press",
  communityGuide: "/resources/community-guide",
  firstMeetChecklist: "/resources/first-meet-checklist",
  helpCenter: "/help",
  status: "/status",
  privacy: "/legal/privacy",
  terms: "/legal/terms",
  communityGuidelines: "/legal/community-guidelines",
  cookieSettings: "/legal/cookies",
  accessibility: "/legal/accessibility",
  signIn: "/sign-in",
  createProfile: "/create-profile",
  otp: "/otp",
  showcase: "/showcase",
} as const;

export type RouteKey = keyof typeof ROUTES;
