export const seedPricingPlans = [
  {
    id: "seed-plan-free",
    name: "Free",
    nickname: "New Friend",
    price: 0,
    interval: "month",
    description: "Create a meaningful profile and start matching without paying.",
    features: [
      "One pet profile",
      "Standard local discovery",
      "Limited daily likes",
      "Basic compatibility details",
      "Match and chat",
      "Safety checklist access",
    ],
    ctaLabel: "Create a free profile",
    featured: false,
    active: true,
  },
  {
    id: "seed-plan-plus",
    name: "Plus",
    nickname: "Best Friend",
    price: 800,
    interval: "month",
    description: "More discovery power when your pack starts to grow.",
    features: [
      "Everything in Free",
      "Unlimited likes",
      "Advanced compatibility filters",
      "See who liked your pet",
      "Extended discovery radius",
      "Profile boost each month",
      "Read receipts",
      "Saved search preferences",
    ],
    ctaLabel: "Try Plus",
    featured: true,
    active: true,
  },
  {
    id: "seed-plan-pack",
    name: "Pack",
    nickname: "Community Pack",
    price: 1600,
    interval: "month",
    description: "Tools for multi-pet households and local community hosts.",
    features: [
      "Everything in Plus",
      "Up to four pet profiles",
      "Create group walks",
      "Host local pet circles",
      "Event planning tools",
      "Priority support",
      "Community moderation controls",
      "Partner discounts (coming soon)",
    ],
    ctaLabel: "Build your pack",
    featured: false,
    active: true,
  },
] as const;
